name: Feature request
description: Suggest lesson, propose new data-structure and algorithms, discuss new ideas
title: "[FEATURE] <description>"
labels: ["⭐ goal: addition"]
body:
  - type: textarea
    id: requesttype
    attributes:
      label: ⭐ Request Type
      description: name of the lesson or section you wanted to add.
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: 💻 Location
      description: |
        Where you think your lesson should be placed(location) so that there will be ease in understanding for new comers.
    validations:
      required: true
  - type: textarea
    id: addtionalinfo
    attributes:
      label: ❌ Additional Info
      description: |
        If you have any additional information that you think will help the community.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join the Discord community [here](#)
